# Generated by Django 4.1.7 on 2023-03-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=20)),
                ('blog_heading', models.CharField(max_length=30)),
                ('blog_notes', models.CharField(max_length=50)),
                ('blog_details', models.TextField(max_length=3000)),
                ('blog_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
