# Generated by Django 4.2.1 on 2023-07-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_heading', models.CharField(max_length=30)),
                ('course_link', models.CharField(max_length=100)),
                ('course_notes', models.TextField(max_length=600)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.CharField(max_length=20)),
                ('service_heading', models.CharField(max_length=50)),
                ('service_note', models.TextField(max_length=200)),
            ],
        ),
    ]
